### PR TITLE
readme for JNI

### PR DESCRIPTION
**Pull request by teytaud**
## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by teytaud** [comment]
@DennisSoemers  adding dependencies in the README

**Comment by teytaud** [comment]
@juliendehos I get a crash at runtime, is everything fine on your side ? which java environment are you using ?

**Comment by juliendehos** [comment]
@teytaud I get a crash too with `master` or `addjni`. But it seems ok with the `ludiitest` branch. My java environment is openjdk-8u222.

**Comment by teytaud** [comment]
@tscmoo  this PR ok for you ?

**Pull request merged**
