### PR TITLE
initial commit Ludii+Polygames

### PR DESCRIPTION
**Pull request by DennisSoemers**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

Initial commit with code for Ludii + Polygames bridge.

## How Has This Been Tested (if it applies)

I think a couple of the files (specifically, the jni_utils ones) do not yet compile in C++, they have syntax errors and are not yet complete. The ludii_game_wrapper and ludii_state_wrapper files should hopefully compile, but could not yet test this to verify because the rest doesn't. So, it'd be good to merge this into a non-master branch for now :)

## Checklist

- [ ] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [ ] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by juliendehos** [comment]
Thanks for this PR.
I fixed some typos about cmake/circleci so I think the circleci logs are more interesting now.

**Comment by juliendehos** [comment]
@DennisSoemers To integrate a game in Polygames, we have to implement two abstract classes: `_Action` and `State` (defined in `core/state.h`). I think `LudiiStateWrapper` can inherit from `State` but  we will need the copy constructor. Is there any special reason to delete the copy constructor in `LudiiStateWrapper` (except to avoid accidental copies) ?

**Comment by DennisSoemers** [comment]
@juliendehos I deleted it for now because I was sure that the default copy constructor that the compiler would generate would be wrong, because it would fail to jump into Java and call the Java copy constructor for the Java object that we wrap around.

So sure, we can have a copy constructor, but it'll have to be a custom implementation to make sure it's correct. The `LudiiStateWrapper::LudiiStateWrapper(JNIEnv* jenv, const LudiiStateWrapper& other)` constructor that I implemented should be correct. If we really need to use the C++ copy ctor without the JNIEnv* argument, that should also be possible -- with a custom implementation similar to the one we have in the current "fake" copy ctor.

**Comment by juliendehos** [comment]
Ok, so I will try to add a copy constructor and to implement `State` and `_Action`.
Thank you.

**Pull request merged**
